<<<<<<< HEAD
=======
  
>>>>>>> a7de46fc713c7978e224e202ad4d4cd99981ec2b
CREATE TABLE lists(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category TEXT NOT NULL,
    name TEXT,
    note TEXT,
    price NUMERIC,
    weight NUMERIC,
    start_date TIMESTAMPTZ DEFAULT now() NOT NULL,
    completed_date TIMESTAMPTZ DEFAULT now() NOT NULL,
    checked BOOLEAN NOT NULL,
    user_id INTEGER 
<<<<<<< HEAD
        REFERENCES users(id) ON DELETE CASCADE
=======
        REFERENCES users(id) ON DELETE CASCADE,
    category_id INTEGER 
        REFERENCES categories(id) ON DELETE CASCADE NOT NULL
>>>>>>> a7de46fc713c7978e224e202ad4d4cd99981ec2b
);